config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}
	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    mailer:        'users/mailer'
	}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # admin
  resources :admins, only: [:index, :edit, :update]
  get 'admin/users' => 'admins#user_index', as:'admin_users'

  # common
  resources :homes, only: [:index]

  # user
  # show edit update destroy
  resources :users do
    member do
      get :following, :followers
      get :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/password/edit' => 'users#password_edit', as: 'edit_password_user'
  patch 'users/:id/password' => 'users#password_update'

  # task_group
  # index create update destroy show
  resources :task_groups
  post 'task_groups/position' => 'task_groups#position_update'
  delete 'task_groups/:id/clear' => 'task_groups#destroy_all', as: 'destroy_all'

  # task
  # update delete create
  resources :tasks do
    resource :task_details, only: [:show]
  end
  get 'tasks/:id/clear' => 'tasks#check'
  post 'tasks/position' => 'tasks#position_update', as: 'update_position'
  post '/task_groups/stage_positions' => 'tasks#stage_position_update'
  patch 'tasks/:task_id/task_details' => 'task_details#update', as: 'update_limit'

  # diary
  # index show new create edit update delete
  resources :diaries do
    resource :diary_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search/diaries' => 'diaries#search', as:'search_diaries'

  # memory_group
  # show update
  resources :memory_groups, except: [:new, :edit] do
    resource :memories, only: [:create, :show]
    resource :memory_stages, only: [:show]
  end
  post 'memory_groups/position' => 'memory_groups#position_update'
  get 'memory_groups/:memory_group_id/step/memories' => 'memories#step_index', as:'step_index'

  # memory
  # index create update delete
  resources :memories
  get 'all_memories' => 'memories#all_show', as: 'all_memories'
  get 'memories/:id/correct' => 'memories#correct', as: 'correct'
  get 'memories/:id/wrong' => 'memories#wrong', as: 'wrong'

  # default_stage
  # index create update destroy
  resources :default_stages, except: [:new, :show, :edit]

  # memory_stage
  # update destroy create
  resources :memory_stages, only: [:create, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :admin_name, presence: true, length: { in: 1..20 }

  attachment :admin_image

end

app/models/default_stage.rb
class DefaultStage < ApplicationRecord

	belongs_to :user

	validates :period, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/diary.rb
class Diary < ApplicationRecord

	belongs_to :user

	has_many :diary_images, dependent: :destroy
	accepts_nested_attributes_for :diary_images, allow_destroy: true

	has_many :diary_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	validates :title, presence: true, length: { maximum: 30 }
	validates :content, presence: true
	validates :diary_date, presence: true
	validates :inform_status, presence: true

	before_create do
		diary_images.each{ |diary_image| diary_image.mark_for_destruction if diary_image.diary_image.blank? }
	end

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search)
		if search
			Diary.where(['(title LIKE ?) OR (content LIKE ?)', "%#{search}%", "%#{search}%"]).where(inform_status: '公開')
		else
			Diary.all
		end
	end

end

app/models/diary_comment.rb
class DiaryComment < ApplicationRecord
	belongs_to :user
	belongs_to :diary

	validates :comment, presence: true

end

app/models/diary_image.rb
class DiaryImage < ApplicationRecord

	belongs_to :diary

	attachment :diary_image

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :diary
end

app/models/memory.rb
class Memory < ApplicationRecord

	belongs_to :memory_group

	attachment :problem_image
	attachment :answer_image

	validates :image_or_conetnt, presence: true

	# before_create do
	# 	problem.mark_for_destruction if problem.problem_content.blank?
	# 	problem_image.mark_for_destruction if problem_image.problem_image.blank?
	# 	answer.mark_for_destruction if answer.answer_content.blank?
	# 	answer_image.mark_for_destruction if answer_image.answer_image.blank?
	# end

	private

    def image_or_conetnt
		problem_image.presence or problem_content.presence
    end

end

app/models/memory_group.rb
class MemoryGroup < ApplicationRecord

	belongs_to :user

	has_many :memories, dependent: :destroy
	has_many :memory_stages, dependent: :destroy

	validates :title, presence: true, length: { in: 1..20 }
	validates :period, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/memory_stage.rb
class MemoryStage < ApplicationRecord

	belongs_to :memory_group

	validates :period, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"

 	validates :following_id, presence: true
 	validates :follower_id, presence: true
end

app/models/task.rb
class Task < ApplicationRecord

	belongs_to :task_group

	has_one :task_detail, dependent: :destroy
	accepts_nested_attributes_for :task_detail, allow_destroy: true

	validates :title, presence: true, length: { in: 1..20 }

end

app/models/task_detail.rb
class TaskDetail < ApplicationRecord
	belongs_to :task
end

app/models/task_group.rb
class TaskGroup < ApplicationRecord

	belongs_to :user

	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, allow_destroy: true

	validates :title, presence: true, length: { in: 1..20 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  validates :name,  uniqueness: { case_sensitive: :true }, length: { minimum: 3, maximum: 10 }

  attachment :profile_image

  has_many :task_groups, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :memory_groups, dependent: :destroy
  has_many :default_stages, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     	user == current_user
  	end
end

app/views/admins/edit.html.erb
<%= stylesheet_link_tag 'admins', media: 'all' %>

<div class="edit-page">
	<div class="container">
		<div class="row">
			<h2>管理者情報 編集</h2>
		</div>
		<div class="row">
			<%= form_for(@admin) do |f| %>
			 	<div class="col-lg-6">
					<table class='table'>
						<tr>
					    	<th><%= attachment_image_tag @admin, :admin_image, format: 'jpeg', fallback: "/images/no_image.jpg", class: "preview" %></th>
					  	</tr>
					  	<tr>
					    	<th><%= f.attachment_field :admin_image %></th>
					  	</tr>
					  	<tr>
					    	<th><%= f.label :admin_name, "名前" %><%= f.text_field :admin_name %></th>
					  	</tr>
					  	<tr>
					    	<th><%= f.label :email %><%= f.email_field :email %></th>
					  	</tr>
					</table>
				<%= f.submit "保存", class: 'btn btn-dark' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	$('input[type=file]').on('change', function (e) {
	    var reader = new FileReader();
	    reader.onload = function (e) {
	        $(".preview" ).attr('src', e.target.result);
	    }
	    reader.readAsDataURL(e.target.files[0]);
	});
</script>

app/views/admins/index.html.erb
<%= stylesheet_link_tag 'admins', media: 'all' %>

<div class="container">
  <div class="row index-page">
    <h2>Admins</h2>
    <table class="table table1">
        <thead>
          <tr>
            <th class="id-th">ID</th>
            <th class="date-th">登録日</th>
            <th class="image-th"></th>
            <th class="admin-name-th">管理者名</th>
            <th></th>
          </tr>
        </thead>

        <% @admins.each do |admin| %>
        <tbody>
          <tr>
            <td><%= admin.id %></td>
            <td><%= admin.created_at.strftime("%Y.%m.%d") %></td>
            <td><%= attachment_image_tag admin, :admin_image, :fill, 30, 30, format: 'jpeg', fallback: "/images/no_image.jpg" %></td>
            <td><%= admin.admin_name %></td>
            <td><%= link_to "編集", edit_admin_path(admin), class: "btn" %></td>
          </tr>
        </tbody>
        <% end %>
    </table>
    <table class="table table2">
        <thead>
          <tr>
            <th class="id-th">ID</th>
            <th class="image-th"></th>
            <th class="admin-name-th">管理者名</th>
            <th></th>
          </tr>
        </thead>

        <% @admins.each do |admin| %>
        <tbody>
          <tr>
            <td><%= admin.id %></td>
            <td><%= attachment_image_tag admin, :admin_image, :fill, 30, 30, format: 'jpeg', fallback: "/images/no_image.jpg" %></td>
            <td><%= admin.admin_name %></td>
            <td><%= link_to "編集", edit_admin_path(admin), class: "btn" %></td>
          </tr>
        </tbody>
        <% end %>
    </table>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<!-- <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %> -->
  <!-- <%= link_to "Forgot your password?", new_password_path(resource_name) %><br /> -->
<!-- <% end -%> -->

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/user_index.html.erb
<%= stylesheet_link_tag 'admins', media: 'all' %>

<div class="container">
  <div class="row user-index">
    <h2>Users</h2>
    <p>総ユーザー <%= @users.size %></p>
    <table class='table'>
        <thead>
          <tr>
            <th>ID</th>
            <th>登録日時</th>
            <th>氏名</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.created_at.strftime("%Y.%m.%d") %></td>
            <td><%= user.name %></td>
          </tr>
        </tbody>
        <% end %>
    </table>
  </div>
</div>