config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}
	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    mailer:        'users/mailer'
	}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # admin
  resources :admins, only: [:index, :edit, :update]
  get 'admin/users' => 'admins#user_index', as:'admin_users'

  # common
  resources :homes, only: [:index]

  # user
  # show edit update destroy
  resources :users do
    member do
      get :following, :followers
      get :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/password/edit' => 'users#password_edit', as: 'edit_password_user'
  patch 'users/:id/password' => 'users#password_update'

  # task_group
  # index create update destroy show
  resources :task_groups
  post 'task_groups/position' => 'task_groups#position_update'
  delete 'task_groups/:id/clear' => 'task_groups#destroy_all', as: 'destroy_all'

  # task
  # update delete create
  resources :tasks do
    resource :task_details, only: [:show]
  end
  get 'tasks/:id/clear' => 'tasks#check'
  post 'tasks/position' => 'tasks#position_update', as: 'update_position'
  post '/task_groups/stage_positions' => 'tasks#stage_position_update'
  patch 'tasks/:task_id/task_details' => 'task_details#update', as: 'update_limit'

  # diary
  # index show new create edit update delete
  resources :diaries do
    resource :diary_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search/diaries' => 'diaries#search', as:'search_diaries'

  # memory_group
  # show update
  resources :memory_groups, except: [:new, :edit] do
    resource :memories, only: [:create, :show]
    resource :memory_stages, only: [:show]
  end
  post 'memory_groups/position' => 'memory_groups#position_update'
  get 'memory_groups/:memory_group_id/step/memories' => 'memories#step_index', as:'step_index'

  # memory
  # index create update delete
  resources :memories
  get 'all_memories' => 'memories#all_show', as: 'all_memories'
  get 'memories/:id/correct' => 'memories#correct', as: 'correct'
  get 'memories/:id/wrong' => 'memories#wrong', as: 'wrong'

  # default_stage
  # index create update destroy
  resources :default_stages, except: [:new, :show, :edit]

  # memory_stage
  # update destroy create
  resources :memory_stages, only: [:create, :update, :destroy]

end

app/models/task_group.rb
class TaskGroup < ApplicationRecord

	belongs_to :user

	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, allow_destroy: true

	validates :title, presence: true, length: { in: 1..20 }

end

app/controllers/task_groups_controller.rb
class TaskGroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only: [:show, :update, :destroy, :destroy_all]

	def index
		@task_groups = current_user.task_groups.order(position_id: :asc)
		@task_group = TaskGroup.new
		@tasks = Task.all
	end

	def create
		@task_group = TaskGroup.new(task_group_params)
		@task_group.user_id = current_user.id
		if @task_group.save
			flash[:notice] = "作成されました。"
		else
			flash[:alert] = "入力エラーが発生しました。リスト名は1~20文字以内です。"
		end
		redirect_back(fallback_location: homes_path)
	end

	def show
		@task_group = TaskGroup.find(params[:id])
		@task_groups = TaskGroup.where.not(id: @task_group.id)
		@tasks = @task_group.tasks
		@task = Task.new
		@task.build_task_detail
	end

	def update
		@task_group = TaskGroup.find(params[:id])
		if @task_group.update(task_group_params)
			flash[:notice] = "更新されました。"
		else
			flash[:alert] = "入力エラーが発生しました。リスト名は1~20文字以内です。"
		end
		redirect_back(fallback_location: homes_path)
	end

	def destroy
		@task_group = TaskGroup.find(params[:id])
		if  @task_group.destroy
		  	flash[:notice] = "削除されました。"
		else
			flash[:alert] = "エラーが発生しました。"
		end
		redirect_back(fallback_location: homes_path)
	end

	def position_update
		result = params[:position]
		result.each.with_index(1) do |id, i|
			@task_group = TaskGroup.find(id)
			@task_group.update(:position_id => i)
		end
	end

	def destroy_all
		@task_group = TaskGroup.find(params[:id])
		if  params[:status] == '3'
			@tasks = @task_group.tasks.where(status: 3)
			@tasks.destroy_all
		  	flash[:notice] = "削除されました。"
		else
			flash[:notice] = "エラーが発生しました。"
		end
		redirect_back(fallback_location: homes_path)
	end

	private

	def task_group_params
		params.require(:task_group).permit(:title, :content, :position_id, :user_id)
	end

	def ensure_correct_user
		@task_group = TaskGroup.find_by(id: params[:id])
        if current_user.id != @task_group.user_id
           flash[:alert] = "アクセス権限がありません。"
           redirect_back(fallback_location: homes_path)
        end
    end
end

app/helpers/task_groups_helper.rb
module TaskGroupsHelper
end

app/views/task_groups/_task.html.erb
<div id="<%= task.id %>" class="task-group">
	<div class="task-box">
		<div class="task-check">
			<input type="checkbox" name="checkbox" class="checkbox" value="/tasks/<%= task.id %>/clear" <% if task.status == 3 %> checked <% end %> />
		</div>
		<div class="detail-box">
			<% if task.task_detail.time_limit.nil? || task.task_detail.time_limit < 1 %>
				<p class="title"><%= task.title %></p>
			<% else %>
				<p class="title"><%= link_to task.title, task_task_details_path(task) %></p>
			<% end %>
			<p class="details">
				<% if task.task_detail.deadline.present? %>
					<%= task.task_detail.deadline.strftime("%Y.%m.%d") %>
				<% end %>
				<% if task.task_detail.time_limit.present? && task.status < 3 %>
					<% hr = task.task_detail.time_limit/3600 %>
					<% min = task.task_detail.time_limit/60%60 %>
					　残り <%= hr %>時間 <%= min %>分
				<% end %>
				<% if task.status == 3 %>
					<a href="#modal<%= task.id %>" data-lity="data-lity"><span class="clear-text">clear</span>＊</a>
				<% else %>
					<a href="#modal<%= task.id %>" data-lity="data-lity">＊</a>
				<% end %>
			</p>
		</div>
	</div>
	<div id="modal<%= task.id %>" class="lity-hide">
		<div class="modal-content">
			<div class="modal-form">
			    <h3>Task edit</h3>
			    <hr>
				<%= form_for task, url: task_path(task) do |f|%>
					<div class="field">
					  	<%= f.label :title, "タスク名" %><br />
					  	<%= f.text_field :title %>
					</div>
					<%= f.fields_for :task_detail do |d| %>
						<div class="field">
							<%= d.label :deadline, "締め切り" %><br />
							<%= d.date_field :deadline %>
						</div>
					<% end %>
					<div class="actions">
					  	<%= f.submit '更新', class: "edit-btn" %>
					</div>
				<% end %>
				<%= link_to "削除", task_path(task), method: :delete, class: 'delete-btn', "data-confirm" => "本当に削除しますか?" %>
			</div>
		</div>
	</div>
</div>

app/views/task_groups/index.html.erb
<%= stylesheet_link_tag "task_groups/index", :media => "all" %>

<main>
	<div class="container">

		<div class="row headline">
			<h2>Task list</h2>
		</div>
		<div class="group-status">
			<% @task_groups.each do |task| %>
				<div id="<%= task.id %>" class="task-group">
					<h4><%= link_to task.title.truncate(20), task_group_path(task), class: "task-title" %></h4>
					<hr>
					<div class="task-content">
						<p class="task-text"><%= task.content %></p>
					</div>
					<div class="task-info">
						<p>InBox : <span class="<% if task.tasks.where(status: 1).size > 0 %>status-color<% end %>"><%= task.tasks.where(status: 1).size %></span></p>
						<p>OnGoing : <span class="<% if task.tasks.where(status: 2).size > 0 %>status-color<% end %>"><%= task.tasks.where(status: 2).size %></span></p>
						<p>Done : <%= task.tasks.where(status: 3).size %></p>
						<p><a href="#edit-modal<%= task.id %>" data-lity="data-lity">＊</a></p>
					</div>

					<div id="edit-modal<%= task.id %>" class="lity-hide">
						<div class="modal-content">
							<div class="modal-form">
							    <h3>List edit</h3>
							    <hr>
								<%= form_for task, url: task_group_path(task)  do |f| %>
									<div class="field">
									  	<%= f.label :title, "リスト名" %><br />
									  	<%= f.text_field :title %>
									</div>
									<div class="field">
										<%= f.label :content, "説明", class: "label-content" %><br />
										<%= f.text_area :content %>
									</div>
									<div class="actions">
									  	<%= f.submit '更新', class: "edit-btn" %>
									</div>
								<% end %>
								<%= link_to "削除", task_group_path(task), method: :delete, class: 'delete-btn', "data-confirm" => "本当に削除しますか?" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<div class="task-group group2">
			<a href="#create-modal" class="plus-mark" data-lity="data-lity">＋</a>
		</div>
		<div id="create-modal" class="lity-hide">
			<div class="modal-content">
				<div class="modal-form">
				    <h3>List create</h3>
				    <hr>
					<%= form_for(@task_group) do |f| %>
						<div class="field">
						  	<%= f.label :title, "リスト名" %><br />
						  	<%= f.text_field :title %>
						</div>
						<div class="field">
							<%= f.label :content, "説明", class: "label-content" %><br />
							<%= f.text_area :content %>
						</div>
						<div class="actions">
						  	<%= f.submit '作成', class: "edit-btn" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</main>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag "task_group.js" %>

app/views/task_groups/show.html.erb
<%= stylesheet_link_tag "task_groups/show", :media => "all" %>

<style type="text/css" media="screen">
	.reload {
		color: red;
		font-size: 20px;
		line-height: 24px;
	}
</style>
<div class="container">
	<div class="row">
		<h2><%= @task_group.title %></h2>
		<p class="plus-mark"><a href="#create-modal" data-lity="data-lity">＋</a>　<span class="reload hide"><i class="fas fa-redo-alt"></i></span></p>
	</div>
	<div class="row task-list">
		<div class="status-box" >
			<a href="#group1" data-lity="data-lity"><h3>InBox <% if @tasks.where(status: 1).length > 0 %>
				<%= @tasks.where(status: 1).length %><% end %></h3></a>
			<div class="status-field status1">
				<% @tasks.where(status: 1).order(position_id: :asc).each do |task| %>
					<%= render 'task_groups/task', task: task %>
				<% end %>
			</div>
		</div>
		<div class="status-box" >
			<a href="#group2" data-lity="data-lity"><h3>OnGoing <% if @tasks.where(status: 2).length > 0 %>
				<%= @tasks.where(status: 2).length %><% end %></h3></a>
			<div class="status-field status2">
				<% @tasks.where(status: 2).order(position_id: :asc).each do |task| %>
				<%= render 'task_groups/task', task: task %>
				<% end %>
			</div>
		</div>
		<div class="status-box" >
			<a href="#group3" data-lity="data-lity"><h3>Done <% if @tasks.where(status: 3).length > 0 %>
				<%= @tasks.where(status: 3).length %><% end %></h3></a>
			<%= link_to "clear", destroy_all_path(@task_group, status: 3), method: :delete, class: 'clear', "data-confirm" => "まとめてclearしますか?" %>
			<div class="status-field status3">
				<% @tasks.where(status: 3).order(position_id: :asc).each do |task| %>
					<%= render 'task_groups/task', task: task %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<%= form_tag update_position_path, :method => 'post', id: "position" do %>
    <input type="hidden" id="result1" name="result1" />
    <input type="hidden" id="result2" name="result2" />
    <input type="hidden" id="result3" name="result3" />
<% end %>

<div id="group1" class="lity-hide">
	<div class="tasks-index">
		<h3>InBox <% if @tasks.where(status: 1).length > 0 %><%= @tasks.where(status: 1).length %><% end %></h3>
		<div class="modal-index">
			<% @tasks.where(status: 1).order(position_id: :asc).each do |task| %>
				<%= render 'task_groups/task', task: task %>
			<% end %>
		</div>
	</div>
</div>

<div id="group2" class="lity-hide">
	<div class="tasks-index">
		<h3>OnGoing <% if @tasks.where(status: 2).length > 0 %><%= @tasks.where(status: 2).length %><% end %></h3>
		<div class="modal-index">
			<% @tasks.where(status: 2).order(position_id: :asc).each do |task| %>
				<%= render 'task_groups/task', task: task %>
			<% end %>
		</div>
	</div>
</div>

<div id="group3" class="lity-hide">
	<div class="tasks-index">
		<h3>Done <% if @tasks.where(status: 3).length > 0 %><%= @tasks.where(status: 3).length %><% end %></h3>
		<div class="modal-index">
			<% @tasks.where(status: 3).order(position_id: :asc).each do |task| %>
				<%= render 'task_groups/task', task: task %>
			<% end %>
		</div>
	</div>
</div>

<div id="create-modal" class="lity-hide">
	<div class="modal-content content2">
		<div class="modal-form">
		    <h3>Task create</h3>
		    <hr>
			<%= form_for @task, url: tasks_path(group_id: @task_group.id),  html: {name: 'task_form'} do |f| %>
				<%= f.hidden_field :status, value: 1 %>
				<div class="field">
				  	<%= f.label :title, "タスク名" %><br />
				  	<%= f.text_field :title %>
				</div>
				<%= f.fields_for :task_detail do |d| %>
					<div class="field">
						<%= d.label :deadline, "締め切り" %><br />
						<%= d.date_field :deadline %>
					</div>
					<div class="field">
						<%= select_tag 'time_required_hr', options_for_select((0..23).to_a,0), name: 'time_required_hr', onchange: "time_required()" %> 時間
						<%= select_tag 'time_required_min',options_for_select([0,5,10,15,20,25,30,35,40,45,50,55],0), name: 'time_required_min', onchange: "time_required()" %> 分
					</div>
					<%= d.hidden_field :time_required, class: 'changetime_required' %>
					<%= d.hidden_field :time_limit, class: 'changetime_required' %>
				<% end %>
				<div class="actions">
				  	<%= f.submit '作成', class: "edit-btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	$(function(){
		$(".reload").click(function(){
			window.location.reload();
		});
	});
	// drag & drop
$(function () {
    $('.modal-index').sortable({
        helper: "clone",
        scroll: true,

        update: function(){
            var result = $(this).sortable("toArray");

            $.ajax({
                url: "/task_groups/stage_positions",
                type:'POST',
                dataType: 'json',
                data : {position : result },
                timeout:3000,
            }).done(function(data) {
            }).fail(function(XMLHttpRequest, textStatus, errorThrown) {
                $(".reload").removeClass('hide');
            })
        }
    });
});
</script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag "task_group.js" %>