config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}
	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    mailer:        'users/mailer'
	}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # admin
  resources :admins, only: [:index, :edit, :update]
  get 'admin/users' => 'admins#user_index', as:'admin_users'

  # common
  resources :homes, only: [:index]

  # user
  # show edit update destroy
  resources :users do
    member do
      get :following, :followers
      get :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/password/edit' => 'users#password_edit', as: 'edit_password_user'
  patch 'users/:id/password' => 'users#password_update'

  # task_group
  # index create update destroy show
  resources :task_groups
  post 'task_groups/position' => 'task_groups#position_update'
  delete 'task_groups/:id/clear' => 'task_groups#destroy_all', as: 'destroy_all'

  # task
  # update delete create
  resources :tasks do
    resource :task_details, only: [:show]
  end
  get 'tasks/:id/clear' => 'tasks#check'
  post 'tasks/position' => 'tasks#position_update', as: 'update_position'
  post '/task_groups/stage_positions' => 'tasks#stage_position_update'
  patch 'tasks/:task_id/task_details' => 'task_details#update', as: 'update_limit'

  # diary
  # index show new create edit update delete
  resources :diaries do
    resource :diary_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search/diaries' => 'diaries#search', as:'search_diaries'

  # memory_group
  # show update
  resources :memory_groups, except: [:new, :edit] do
    resource :memories, only: [:create, :show]
    resource :memory_stages, only: [:show]
  end
  post 'memory_groups/position' => 'memory_groups#position_update'
  get 'memory_groups/:memory_group_id/step/memories' => 'memories#step_index', as:'step_index'

  # memory
  # index create update delete
  resources :memories
  get 'all_memories' => 'memories#all_show', as: 'all_memories'
  get 'memories/:id/correct' => 'memories#correct', as: 'correct'
  get 'memories/:id/wrong' => 'memories#wrong', as: 'wrong'

  # default_stage
  # index create update destroy
  resources :default_stages, except: [:new, :show, :edit]

  # memory_stage
  # update destroy create
  resources :memory_stages, only: [:create, :update, :destroy]

end

app/models/memory_group.rb
class MemoryGroup < ApplicationRecord

	belongs_to :user

	has_many :memories, dependent: :destroy
	has_many :memory_stages, dependent: :destroy

	validates :title, presence: true, length: { in: 1..20 }
	validates :period, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/controllers/memory_groups_controller.rb
class MemoryGroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, except: [:index, :create, :position_update]

	def index
		@memory_groups = current_user.memory_groups.order(position_id: :asc)
		@all_memories = 0
		@memory_groups.each do |mg|
			if mg.loop == 1
				@all_memories += mg.memories.where("execution_date <= ?", Date.current).size
			else
				@all_memories += mg.memories.where.not(stage: 0).where("execution_date <= ?", Date.current).size
			end
		end
		@memory_group = MemoryGroup.new
	end

	def create
		@memory_group = MemoryGroup.new(memory_group_params)
		@memory_group.user_id = current_user.id
		if @memory_group.save
			current_user.default_stages.each do |d|
				@memory_stage = MemoryStage.new
				@memory_stage.memory_group_id = @memory_group.id
				@memory_stage.stage = d.stage
				@memory_stage.period = d.period
				@memory_stage.save
			end
			flash[:notice] = "作成されました。"
		else
			flash[:alert] = "入力エラーが発生しました。リスト名は1~20文字以内です。"
		end
		redirect_back(fallback_location: homes_path)
	end

	def show
		@memory_group = MemoryGroup.find(params[:id])
		if @memory_group.loop == 1
			@today_memories = @memory_group.memories.where("execution_date <= ?", Date.current)
		else
			@today_memories = @memory_group.memories.where.not(stage: 0).where("execution_date <= ?", Date.current)
		end
		@memory = Memory.new
		@maxNum = @today_memories.where(stage: 1).length
		@maxStage = 1
		@memory_group.memory_stages.each do |s|
			if @today_memories.where(stage: s.stage).length > @maxNum
				@maxNum = @today_memories.where(stage: s.stage).length
				@maxStage = s.stage
			end
		end
	end

	def update
		@memory_group = MemoryGroup.find(params[:id])
		if @memory_group.update(memory_group_params)
			flash[:notice] = "更新されました。"
		else
			if params[:stage] == 'loop'
				flash[:alert] = "入力エラーが発生しました。期間は1日以上に設定して下さい。"
			else
				flash[:alert] = "入力エラーが発生しました。リスト名は1~20文字以内です。"
			end
		end
		redirect_back(fallback_location: homes_path)
	end

	def destroy
		@memory_group = MemoryGroup.find(params[:id])
		if  @memory_group.destroy
		  	flash[:notice] = "削除されました。"
		else
			flash[:alert] = "エラーが発生しました。"
		end
		redirect_to memory_groups_path
	end

	def position_update
		result = params[:position]
		i = 1
		result.each do |id|
			if id != "none"
				@memory_group = MemoryGroup.find(id)
				@memory_group.update(:position_id => i)
				i += 1
			end
		end
	end

	private

	def memory_group_params
		params.require(:memory_group).permit(
			:title, :content, :loop, :period, :untie, :user_id,
			memory_stages_attributes: [:id, :stage, :period, :memory_group_id, :position_id, :_destroy]
		)
	end

	def ensure_correct_user
		@memory_group = MemoryGroup.find_by(id: params[:id])
        if current_user.id != @memory_group.user_id
           flash[:alert] = "アクセス権限がありません。"
           redirect_to homes_path
        end
    end
end

app/helpers/memory_groups_helper.rb
module MemoryGroupsHelper
end

app/views/memory_groups/index.html.erb
<%= stylesheet_link_tag "memory_groups/index", :media => "all" %>

<main>
	<div class="container">

		<div class="row headline">
			<h2>Memory list</h2>
			<%= link_to 'default step', default_stages_path, class: "stage-link" %>
		</div>
		<div class="group-status">
			<div id="none"class="memory-group stop">
				<h4><%= link_to "All memries", all_memories_path, class: "memory-title" %></h4>
				<hr>
				<div class="memory-content">
						<p class="memory-text"></p>
					</div>
				<div class="memory-info">
					<p>today：<span class="<% if @all_memories > 0 %>status-color<% end %>"><%= @all_memories %></span> 個</p>
					<p></p>
				</div>
			</div>
			<% @memory_groups.each do |mg| %>
				<div id="<%= mg.id %>" class="memory-group">
					<h4><%= link_to mg.title.truncate(16), memory_group_path(mg), class: "memory-title" %></h4>
					<hr>
					<div class="memory-content">
						<p class="memory-text"><%= mg.content %></p>
					</div>
					<div class="memory-info">
						<% if mg.loop == 1 %>
							<p>today：<span class="<% if mg.memories.where("execution_date <= ?", Date.current).size > 0 %>status-color<% end %>"><%= mg.memories.where("execution_date <= ?", Date.current).size %></span> 個</p>
						<% else %>
							<p>today：<span class="<% if mg.memories.where.not(stage: 0).where("execution_date <= ?", Date.current).size > 0 %>status-color<% end %>"><%= mg.memories.where.not(stage: 0).where("execution_date <= ?", Date.current).size %></span> 個</p>
						<% end %>
						<p><a href="#edit-modal<%= mg.id %>" data-lity="data-lity">＊</a></p>
					</div>

					<div id="edit-modal<%= mg.id %>" class="lity-hide">
						<div class="modal-content">
							<div class="modal-form">
							    <h3>List edit</h3>
							    <hr>
								<%= form_for mg, url: memory_group_path(mg)  do |f| %>
									<div class="field">
									  	<%= f.label :title, "リスト名" %><br />
									  	<%= f.text_field :title %>
									</div>
									<div class="field">
										<%= f.label :content, "説明", class: "label-content" %><br />
										<%= f.text_area :content %>
									</div>
									<div class="actions">
									  	<%= f.submit '更新', class: "edit-btn" %>
									</div>
								<% end %>
								<%= link_to "削除", memory_group_path(mg), method: :delete, class: 'delete-btn', "data-confirm" => "本当に削除しますか?" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<div class="memory-group group2">
			<a href="#create-modal" class="plus-mark" data-lity="data-lity">＋</a>
		</div>
		<div id="create-modal" class="lity-hide">
			<div class="modal-content">
				<div class="modal-form">
				    <h3>List create</h3>
				    <hr>
					<%= form_for(@memory_group) do |f| %>
						<div class="field">
						  	<%= f.label :title, "リスト名" %><br />
						  	<%= f.text_field :title %>
						</div>
						<div class="field">
							<%= f.label :content, "説明", class: "label-content" %><br />
							<%= f.text_area :content %>
						</div>
						<div class="actions">
						  	<%= f.submit '作成', class: "edit-btn" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</main>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag "memory_group.js" %>

app/views/memory_groups/show.html.erb
<%= stylesheet_link_tag "memory_groups/show", :media => "all" %>

<style type="text/css" media="screen">
	.today-box {
 	 	min-width: 50vw;
 	 	<% if @memory_group.memory_stages.present? %>
 	 		<% if @memory_group.loop == 1 %>
 	 			width: <%= (@memory_group.memory_stages.size + 1) * 9 %>vw;
 	 		<% else %>
 	 			width: <%= (@memory_group.memory_stages.size) * 10 %>vw;
 	 		<% end %>
 	 	<% end %>
	}
	.modal-form .edit-btn {
	    margin-bottom: 20px;
	}
</style>

<div class="container">
	<div class="row headline">
		<h2><%= @memory_group.title.truncate(19) %></h2>
		<p><%= @memory_group.content %></p>
		<ul>
			<li><a href="#create-modal" class="new-memory" data-lity="data-lity">new memory</a></li>
			<li><%= link_to "all memories", memories_path(group: @memory_group) %></li>
			<li><%= link_to 'step list', memory_group_memory_stages_path(@memory_group), class: "stage-link" %></li>
		</ul>
	</div>
	<hr>
	<div class="today-box">
		<h3>List of today</h3>
  		<div class="folder-tabs">
  			<% if @today_memories.present? %>
  				<div class="first-tab"><%= link_to "All Step", memory_group_memories_path(@memory_group, stage: "all") %></div>
			    <% if @today_memories.where(stage: 1).present? %>
			    	<div class="behind-tab"><%= link_to "Step1", memory_group_memories_path(@memory_group, stage: 1) %></div>
			    <% end %>
			    <% @memory_group.memory_stages.where.not(stage: nil).each do |n| %>
		    		<% if @today_memories.where(stage: n.stage).present? %>
			    		<div class="behind-tab">
			    			<%= link_to memory_group_memories_path(@memory_group, stage: n.stage) do %>Step<%= n.stage %><% end %>
			    		</div>
			    	<% end %>
			    <% end %>
			<% end %>
		    <% if @memory_group.loop == 1 %>
		    	<% if @today_memories.where(stage: 0).present? %>
			    	<div class="behind-tab"><%= link_to "Comp", memory_group_memories_path(@memory_group, stage: 0) %></div>
			    <% end %>
		    <% end %>
  		</div>
		<div class="folder-body">
			<ul class="chart">
				<li>
					<span style="height:<% if @today_memories.where(stage: 1).empty? %>0
										<% elsif @maxStage == 1 %>300px
										<% else %><%= 300 * @today_memories.where(stage: 1).size / @maxNum + 1 %>px
										<% end %>" title="step1">
						<p class="stage-period">
							<% if @today_memories.where(stage: 1).empty? %><span class="clear">clear</span>
							<% else %><%= @today_memories.where(stage: 1).size %>個<% end %></p>
					</span>
				</li>
				<% @memory_group.memory_stages.where.not(stage: nil).each do |n| %>
					<li>
						<span style="height:
									<% if @today_memories.where(stage: n.stage).empty? %>0
									<% elsif @maxStage == n.stage %>300px
									<% else %><%= 300 * @today_memories.where(stage: n.stage).size / @maxNum + 1 %>px
									<% end %>" title="step<%= n.stage %>">
							<p class="stage-period">
								<% if @today_memories.where(stage: n.stage).empty? %><span class="clear">clear</span>
								<% else %><%= @today_memories.where(stage: n.stage).size %>個<% end %></p>
						</span>
					</li>
				<% end %>
				<% if @memory_group.loop == 1 %>
					<li>
						<span style="height:
									<% if @today_memories.where(stage: 0).empty? %>0
									<% elsif @maxStage == 0 %>300px
									<% else %><%= 100 * @today_memories.where(stage: 0).size / @maxNum + 1 %>px
									<% end %>" title="comp">
							<p class="stage-period">
								<% if @today_memories.where(stage: 0).empty? %><span class="clear">clear</span>
								<% else %><%= @today_memories.where(stage: 0).size %>個<% end %></p>
						</span></li>
				<% end %>
			</ul>
		</div>
		<div id="create-modal" class="lity-hide">
		 	<div class="modal-content">
				<div class="modal-form">
				    <h3>Memory create</h3>
				    <hr>
				    <%= form_for [@memory_group,@memory], html: {name: 'form1'} do |f| %>
					    <div class="problem-box">
							<div class="field">
								<label class="label-box" for="memory_problem_image">
							      <div class="img-box">
							        <img class="preview_memory_problem_image" >
							        <i class="far fa-image"></i>
							      </div>
							    </label>
								<%= f.attachment_field :problem_image %>
							</div>
							<div class="field">
								<%= f.label :problem_content %><br />
								<%= f.text_area :problem_content %>
							</div>
					    </div>
					    <div class="answer-box">
							<div class="field">
								<label class="label-box" for="memory_answer_image">
									<div class="img-box">
										<img class="preview_memory_answer_image" >
										<i class="far fa-image"></i>
									</div>
								</label>
								<%= f.attachment_field :answer_image %>
							</div>
							<div class="field">
								<%= f.label :answer_content %><br />
								<%= f.text_area :answer_content %>
							</div>
					    </div>
						<div class="actions">
							<%= f.submit '作成', class: "edit-btn", onClick: "return checkForm();" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="today-box2">
		<h3>List of today</h3>
		<table class='table'>
			<tbody>
				<% if @memory_group.loop == 1 && @today_memories.present? %>
					<tr>
						<td><%= link_to "All Step", memory_group_memories_path(@memory_group, stage: "all") %></td>
						<td><%= @today_memories.size %> 個</td>
					</tr>
				<% elsif @memory_group.loop == 0 && @today_memories.present? %>
					<tr>
						<td><%= link_to "All Step", memory_group_memories_path(@memory_group, stage: "all") %></td>
						<td><%= @today_memories.size %> 個</td>
					</tr>
				<% else %>
					<tr>
						<td>All Step</td>
						<td>0 個</td>
					</tr>
				<% end %>
				<% if @today_memories.where(stage: 1).present? %>
					<tr>
						<td><%= link_to "Step1", memory_group_memories_path(@memory_group, stage: 1) %></td>
						<td><%= @today_memories.where(stage: 1).size %> 個</td>
					</tr>
				<% else %>
					<tr>
						<td>Step1</td>
						<td>0 個</td>
					</tr>
				<% end %>
				<% @memory_group.memory_stages.where.not(stage: nil).each do |n| %>
					<% if @today_memories.where(stage: n.stage).present? %>
						<tr>
							<td>
								<%= link_to memory_group_memories_path(@memory_group, stage: n.stage) do %>
									Step <%= n.stage %>
								<% end %>
							</td>
							<td><%= @today_memories.where(stage: n.stage).size %> 個</td>
						</tr>
					<% else %>
						<tr>
							<td>Step<%= n.stage %></td>
							<td>0 個</td>
						</tr>
					<% end %>
				<% end %>
				<% if @memory_group.loop == 1 %>
					<% if @today_memories.present? %>
						<tr>
							<td><%= link_to "Comp", memory_group_memories_path(@memory_group, stage: 0) %></td>
							<td><%= @today_memories.where(stage: 0).size %> 個</td>
						</tr>
					<% else %>
						<tr>
							<td>Comp</td>
							<td>0 個</td>
						</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
		<div class="modal-form">
		    <h3>Memory create</h3>
		    <hr>
		    <%= form_for [@memory_group,@memory], html: {name: 'modal_form'} do |f| %>
			    <div class="problem-box">
					<div class="field">
						<label class="label-box" for="memory_problem_image_attributes_problem_image1">
					      <div class="img-box">
					        <img class="preview_memory_problem_image_attributes_problem_image1" >
					        <i class="far fa-image"></i>
					      </div>
					    </label>
						<%= f.attachment_field :problem_image, id: 'memory_problem_image_attributes_problem_image1' %>
					</div>
					<div class="field">
						<%= f.label :problem_content %><br />
						<%= f.text_area :problem_content %>
					</div>
			    </div>
			    <div class="answer-box">
					<div class="field">
						<label class="label-box" for="memory_answer_image_attributes_answer_image1">
							<div class="img-box">
								<img class="preview_memory_answer_image_attributes_answer_image1" >
								<i class="far fa-image"></i>
							</div>
						</label>
						<%= f.attachment_field :answer_image, id: 'memory_answer_image_attributes_answer_image1' %>
					</div>
					<div class="field">
						<%= f.label :answer_content %><br />
						<%= f.text_area :answer_content %>
					</div>
			    </div>
				<div class="actions">
					<%= f.submit '作成', class: "edit-btn", onClick: "return checkForm2();" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	$('input[type=file]').on('change', function (e) {
		var str = $(this).attr("id");
	    var reader = new FileReader();
	    reader.onload = function (e) {
	        $(".preview_" + str).attr('src', e.target.result);
	    }
	    reader.readAsDataURL(e.target.files[0]);
	});
	function checkForm(){
	    if(document.form1.memory_problem_content.value == "" && document.form1.memory_problem_image.value == ""){
	        alert("problemフォームには、最低1項目の入力が必要です。");
			return false;
	    }else{
			return true;
	    }
	};
	function checkForm2(){
	    if(document.modal_form.memory_problem_content.value == "" && document.getElementById("memory_problem_image_attributes_problem_image1").value == ""){
	        alert("problemフォームには、最低1項目の入力が必要です。");
			return false;
	    }else{
			return true;
	    }
	}
</script>