config/routes.rb
Rails.application.routes.draw do

  root "homes#index"

  devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}
	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    mailer:        'users/mailer'
	}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # admin
  resources :admins, only: [:index, :edit, :update]
  get 'admin/users' => 'admins#user_index', as:'admin_users'

  # common
  resources :homes, only: [:index]

  # user
  # show edit update destroy
  resources :users do
    member do
      get :following, :followers
      get :favorites
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/password/edit' => 'users#password_edit', as: 'edit_password_user'
  patch 'users/:id/password' => 'users#password_update'

  # task_group
  # index create update destroy show
  resources :task_groups
  post 'task_groups/position' => 'task_groups#position_update'
  delete 'task_groups/:id/clear' => 'task_groups#destroy_all', as: 'destroy_all'

  # task
  # update delete create
  resources :tasks do
    resource :task_details, only: [:show]
  end
  get 'tasks/:id/clear' => 'tasks#check'
  post 'tasks/position' => 'tasks#position_update', as: 'update_position'
  post '/task_groups/stage_positions' => 'tasks#stage_position_update'
  patch 'tasks/:task_id/task_details' => 'task_details#update', as: 'update_limit'

  # diary
  # index show new create edit update delete
  resources :diaries do
    resource :diary_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search/diaries' => 'diaries#search', as:'search_diaries'

  # memory_group
  # show update
  resources :memory_groups, except: [:new, :edit] do
    resource :memories, only: [:create, :show]
    resource :memory_stages, only: [:show]
  end
  post 'memory_groups/position' => 'memory_groups#position_update'
  get 'memory_groups/:memory_group_id/step/memories' => 'memories#step_index', as:'step_index'

  # memory
  # index create update delete
  resources :memories
  get 'all_memories' => 'memories#all_show', as: 'all_memories'
  get 'memories/:id/correct' => 'memories#correct', as: 'correct'
  get 'memories/:id/wrong' => 'memories#wrong', as: 'wrong'

  # default_stage
  # index create update destroy
  resources :default_stages, except: [:new, :show, :edit]

  # memory_stage
  # update destroy create
  resources :memory_stages, only: [:create, :update, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  validates :name,  uniqueness: { case_sensitive: :true }, length: { minimum: 3, maximum: 10 }

  attachment :profile_image

  has_many :task_groups, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :memory_groups, dependent: :destroy
  has_many :default_stages, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     new_user_session_path
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :password_edit, :password_update]

	def show
	  	@user = User.find(params[:id])
	  	if user_signed_in?
			if current_user.id == @user.id
	  	    	@diaries = @user.diaries.order(id: :desc)
	  	    else
	  	    	@diaries = @user.diaries.where(inform_status: '公開').order(id: :desc)
	  	    end
	  	else
	  		@diaries = @user.diaries.where(inform_status: '公開').order(id: :desc)
	  	end
	end

	def favorites
		@user = User.find(params[:id])
		@favorites = @user.favorites.order(id: :desc)
	end

	def edit
		@user = User.find(current_user.id)
	end

	def update
		@user = User.find(current_user.id)
	    if @user.update(user_params)
	    	flash[:notice] = "更新されました。"
	    	redirect_to user_path(@user)
	    else
	    	render 'edit'
	    end
	end

	def destroy
		@user = User.find(current_user.id)
		if  @user.destroy
		  	flash[:notice] = "退会しました。"
		else
			flash[:alert] = "エラーが発生しました。"
		end
		redirect_to homes_path
	end

	def password_edit
		@user = User.find(current_user.id)
	end

	def password_update
	    @user = User.find(current_user.id)
	    if @user.update_with_password(user_params)
	      	bypass_sign_in(@user)
			flash[:notice] = "パスワードを変更しました。"
			redirect_to user_path(@user)
	    else
	        render 'password_edit'
	    end
	end

	def following
		@user  = User.find(params[:id])
		@users = @user.followings
		if @users.present?
			render 'show_follow'
		else
			redirect_back(fallback_location: homes_path)
		end
	end

	def followers
		@user  = User.find(params[:id])
		@users = @user.followers
		if @users.present?
			render 'show_follower'
		else
			redirect_back(fallback_location: homes_path)
		end
	end

	private

	def user_params
	    params.require(:user).permit(:email, :name, :profile_image, :email, :password, :password_confirmation, :current_password, :public_setting)
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     	user == current_user
  	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォロー", class: "btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<% if @user.followings.count > 0 %>
		<a href="<%= following_user_path(@user) %>">
			<strong id="following" class="stat"><%= @user.followings.count %></strong>
			フォロー
		</a>
	<% else %>
		<strong id="following" class="stat"><%= @user.followings.count %></strong>フォロー
	<% end %>
	<% if @user.followers.count > 0 %>
		<a href="<%= followers_user_path(@user) %>"><strong id="followers" class="stat">　<%= @user.followers.count %></strong>
			フォロワー
		</a>
	<% else %>
		<strong id="followers" class="stat">　<%= @user.followers.count %></strong>フォロワー
	<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn1" %>
<% end %>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "users/edit", :media => "all" %>

<div class="container">
	<div class="row">
		<h2><%= link_to "Profile edit", user_path(current_user.id) %></h2>
		<%= form_for(@user) do |f| %>
		 	<div class="edit-table">
				<table class='table'>
					<tr>
				    	<th>
				    		<label class="label-box" for="user_profile_image">
        						<div class="img-box">
          							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/no_image.jpg", class: "preview" %>
						        </div>
						     </label>
						     <%= f.attachment_field :profile_image %>
						</th>
				  	</tr>
				  	<tr>
				    	<th><%= f.label :name, "お名前", class: 'label1' %></th>
				    	<th><%= f.text_field :name %></th>
				  	</tr>
				  	<tr>
				    	<th><%= f.label :email, class: 'label1' %></th>
				    	<th><%= f.email_field :email %></th>
				  	</tr>
				  	<tr>
				  		<th><%= f.label :public_setting, "プライベート設定", class: 'label1' %></th>
				    	<th>
				    		<div class="pretty p-switch p-fill">
        						<%= f.check_box :public_setting %>
    							<div class="state p-success">
        							<label>diaryを公開する</label>
    							</div>
    						</div>
				    	</th>
				  	</tr>
				</table>
				<%= f.submit "保存", class: 'edit-btn' %>
				<%= link_to "退会", user_path(current_user.id), method: :delete, class: 'btn delete-btn', "data-confirm" => "本当に退会しますか?" %>
			</div>
		<% end %>
	</div>
</div>

<%= javascript_include_tag "user.js" %>

app/views/users/favorites.html.erb
<%= stylesheet_link_tag "diaries/index", :media => "all" %>

<div class="container">
	<div class="row diary-main">
		<h2 class="favorite-title">Favorite diaries</h2>
		<div class="diary-box">
			<% if @favorites.blank? %>
				<%= link_to '日記一覧へ', diaries_path, class: "btn" %>
			<% end %>
			<% @favorites.each do |f| %>
				<% if f.diary.diary_images.exists? %>
					<div class="diary-list">
						<div class="img-box">
							<%= attachment_image_tag f.diary.diary_images[0], :diary_image, format: 'jpeg' %>
						</div>
						<div class="diary-content">
							<h4><%= f.diary.title.truncate(18) %></h4>
							<p><%= f.diary.content.truncate(80) %></p>
						</div>
						<p class="date"><%= f.diary.diary_date.strftime("%Y.%m.%d") %></p>
						<%= link_to 'more', diary_path(f.diary), class: "btn" %>
					</div>
				<% else %>
					<div class="diary-list list2">
						<div class="diary-content">
							<h4><%= f.diary.title.truncate(40) %></h4>
							<p><%= f.diary.content.truncate(300) %></p>
						</div>
						<p class="date"><%= f.diary.diary_date.strftime("%Y.%m.%d") %></p>
						<%= link_to 'more', diary_path(f.diary), class: "btn" %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/password_edit.html.erb
<%= stylesheet_link_tag "users/password_edit", :media => "all" %>

<div class="materialContainer">
   <div class="box">
      <div class="title"><%= link_to " パスワードの変更", user_path(current_user.id) %></div>
      <%= form_for(@user, :url => { :action => "password_update" } ) do |f| %>
        <div class="input">
          <%= f.label :current_password, "現在のパスワード" %><br />
          <%= f.password_field :current_password, autocomplete: "off" %>
          <span class="spin"></span>
        </div>

        <div class="input">
          <%= f.label :password, '新しいパスワード' %><br />
          <%= f.password_field :password, autocomplete: "off" %>
          <span class="spin"></span>
        </div>

        <div class="input">
          <%= f.label :password_confirmation, '新しいパスワードを再入力' %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
          <span class="spin"></span>
        </div>

        <div class="button login">
          <button><span>Update</span><i class="fa fas fa-tasks"></i><%= f.submit "ログイン", class: 'submit-btn' %></button>
        </div>
      <% end %>
   </div>
</div>

<script>
  $(function() {

   $(".input input").focus(function() {

      $(this).parent(".input").each(function() {
         $("label", this).css({
            "line-height": "18px",
            "font-size": "18px",
            "font-weight": "100",
            "top": "0px"
         })
         $(".spin", this).css({
            "width": "100%"
         })
      });
   }).blur(function() {
      $(".spin").css({
         "width": "0px"
      })
      if ($(this).val() == "") {
         $(this).parent(".input").each(function() {
            $("label", this).css({
               "line-height": "60px",
               "font-size": "24px",
               "font-weight": "300",
               "top": "10px"
            })
         });

      }
   });

   $(".button").click(function(e) {
      var pX = e.pageX,
         pY = e.pageY,
         oX = parseInt($(this).offset().left),
         oY = parseInt($(this).offset().top);

      $(this).append('<span class="click-efect x-' + oX + ' y-' + oY + '" style="margin-left:' + (pX - oX) + 'px;margin-top:' + (pY - oY) + 'px;"></span>')
      $('.x-' + oX + '.y-' + oY + '').animate({
         "width": "500px",
         "height": "500px",
         "top": "-250px",
         "left": "-250px",

      }, 600);
      $("button", this).addClass('active');
   })
  });
</script>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users/show", :media => "all" %>

<div class="container">
	<div class="row">
		<h2><% if current_user?(@user) %>My page<% else %><%= @user.name %> info<% end %></h2>
		<% if current_user?(@user) %>
			<div class="link">
				<%= link_to "設定", edit_user_path(current_user), class: "btn" %>
				<%= link_to "パスワード変更はこちら", edit_password_user_path(current_user), class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="row">
		<div class="box1">
			<table class='table'>
				<tr>
			    	<th class="first-th">
			    		<a href="#lity" data-lity="data-lity">
			    			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/no_image.jpg" %>
			    		</a>
		    			<div id="lity" class="lity-hide">
		    				<%= attachment_image_tag @user, :profile_image, :fill, 800, 500, format: 'jpeg', fallback: "/images/no_image.jpg" %>
		    			</div>
			    	</th>
			  	</tr>
			  	<tr>
			    	<th><%= @user.name %></th>
			  	</tr>
			  	<% if current_user?(@user) %>
				  	<tr>
				    	<th><%= @user.email %></th>
				  	</tr>
			  	<% end %>
			  	<tr>
			    	<th><%= render 'stats' %></th>
			  	</tr>
			  	<% if user_signed_in? && current_user.id != @user.id %>
			  		<tr>
				    	<th><%= render 'follow_form' %></th>
				  	</tr>
			  	<% end %>
			  	<tr>
			    	<th><%= link_to 'favorite diaries', favorites_user_path(@user), class: "btn favorite" %></th>
			  	</tr>
			</table>
		</div>
		<div class="box2">
			<h2>diary list</h2>
			<div class="diary-box">
				<% @diaries.each do |d| %>
					<% if d.diary_images.exists? %>
						<div class="diary-list">
							<div class="img-box">
								<%= attachment_image_tag d.diary_images[0], :diary_image, format: 'jpeg' %>
							</div>
							<div class="diary-content">
								<h4><%= d.title.truncate(18) %></h4>
								<p><%= d.content.truncate(80) %></p>
							</div>
							<p class="date"><%= d.diary_date.strftime("%Y.%m.%d") %></p>
							<%= link_to 'more', diary_path(d), class: "btn" %>
						</div>
					<% else %>
						<div class="diary-list list2">
							<div class="diary-content">
								<h4><%= d.title.truncate(40) %></h4>
								<p><%= d.content.truncate(300) %></p>
							</div>
							<p class="date"><%= d.diary_date.strftime("%Y.%m.%d") %></p>
							<%= link_to 'more', diary_path(d), class: "btn" %>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<%= stylesheet_link_tag "users/follow", :media => "all" %>

<div class="container">
	<h2><%= link_to user_path(@user) do %><%= @user.name %> followings<% end %></h2>
	<div class="card-box">
		<% @user.followings.each do |user| %>
			<div class="card">
			    <div class="box">
			        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "/images/no_image.jpg", class: 'image' %>
		            <p class="title"><%= user.name %></p>
		            <p class="content"><%= link_to 'more', user_path(user) %></p>
			    </div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show_follower.html.erb
<%= stylesheet_link_tag "users/follow", :media => "all" %>

<div class="container">
	<h2><%= link_to user_path(@user) do %><%= @user.name %> followers<% end %></h2>
	<div class="card-box">
		<% @user.followers.each do |user| %>
			<div class="card">
			    <div class="box">
			        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "/images/no_image.jpg", class: 'image' %>
		            <p class="title"><%= user.name %></p>
		            <p class="content"><%= link_to 'more', user_path(user) %></p>
			    </div>
			</div>
		<% end %>
	</div>
</div>